### ISSUE TITLE
MainPage.java loading the system file

### ISSUE THREAD

**Issue by gateslm** [the-machine-project/the-machine#24]
I was able to correct the code on my computer, but was wondering if there was a general fix for the people playing with the code. 

The system load requires uses the user directory to load the opencv_java***.dll file, however, the code looks for the file in the directory the project is in, not the C: file like the tutorial said. Is there a way to automatically fix this for people playing with the code or should we just deal with it?

Also, is there a way to generalize the open_java***.java to allow any version?

**Comment by devloop0** [comment]
Thanks for bringing this to my attention, I'll add this to the README.md. The reason we also link a copy of the opencv/ directory locally within the project is because if you look at the our distributed binary, you can see that we need to ship the actual opencv DLL to load. If you leave a local copy, that should do it.
At this point, the project needs a copy of the opencv/ directory in the C:\ and a copy of the opencv/ directory in the project folder. You could technically just condense this into the project directory, but you cannot just leave everything in the C:\ directory, as there is no guarantee that an end user has opencv.
As for generalizing opencv_java***.dll, I would be welcome to an suggestions/pull requests, but I cannot see any way of doing this other than hard-coding.
If there is nothing else, I will close this issue.
